#!/bin/bash
# Create a new Supabase instance per domain
# Usage: ./create-project.sh <project_slug> <domain>
# Example: ./create-project.sh bolt3 bolt3.pdfsaas.com
#
# Result: API at https://api.bolt3.pdfsaas.com (via Traefik)

set -e

SLUG="$1"
DOMAIN="$2"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="${SCRIPT_DIR}/projects/${SLUG}"
SUPABASE_DIR="${SCRIPT_DIR}/supabase"

if [ -z "$SLUG" ] || [ -z "$DOMAIN" ]; then
  echo "Usage: $0 <project_slug> <domain>"
  echo "Example: $0 bolt3 bolt3.pdfsaas.com"
  exit 1
fi

# Validate slug (alphanumeric, hyphens)
if ! [[ "$SLUG" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
  echo "Error: slug must be lowercase alphanumeric with hyphens (e.g. bolt3)"
  exit 1
fi

echo "Creating Supabase project: $SLUG for domain $DOMAIN"
mkdir -p "$PROJECT_DIR"

# Clone Supabase if not present (backend pre-clones on startup; this is fallback)
if [ ! -d "$SUPABASE_DIR/docker" ]; then
  if [ ! -d "$SUPABASE_DIR" ]; then
    echo "Cloning Supabase docker..."
    git clone --depth 1 https://github.com/supabase/supabase.git "$SUPABASE_DIR"
  else
    echo "Supabase repo incomplete. Remove and retry: rm -rf $SUPABASE_DIR"
    exit 1
  fi
fi

# Generate secrets using Supabase's script if available
if [ -f "$SUPABASE_DIR/docker/utils/generate-keys.sh" ]; then
  echo "Generating keys with Supabase script..."
  KEY_OUTPUT=$(cd "$SUPABASE_DIR/docker" && ./utils/generate-keys.sh 2>/dev/null || true)
  if [ -n "$KEY_OUTPUT" ]; then
    eval "$(echo "$KEY_OUTPUT" | grep -E '^(JWT_SECRET|ANON_KEY|SERVICE_ROLE_KEY|SECRET_KEY_BASE|VAULT_ENC_KEY|PG_META_CRYPTO_KEY|LOGFLARE_PUBLIC_ACCESS_TOKEN|LOGFLARE_PRIVATE_ACCESS_TOKEN|POSTGRES_PASSWORD|DASHBOARD_PASSWORD)=')"
  fi
fi

# Fallback if keygen failed
: "${JWT_SECRET:=$(openssl rand -base64 48 | tr -d '\n' | head -c 64)}"
: "${POSTGRES_PASSWORD:=$(openssl rand -hex 16)}"
: "${SECRET_KEY_BASE:=$(openssl rand -base64 48 | tr -d '\n')}"
: "${VAULT_ENC_KEY:=$(openssl rand -hex 16)}"
: "${PG_META_CRYPTO_KEY:=$(openssl rand -base64 24 | tr -d '\n')}"
: "${LOGFLARE_PUBLIC_ACCESS_TOKEN:=$(openssl rand -hex 16)}"
: "${LOGFLARE_PRIVATE_ACCESS_TOKEN:=$(openssl rand -hex 16)}"
: "${DASHBOARD_PASSWORD:=$(openssl rand -hex 16)}"

# Anon/service keys must be valid JWTs signed with JWT_SECRET - use keygen or placeholder
if [ -z "$ANON_KEY" ] || [ "${#ANON_KEY}" -lt 50 ]; then
  echo "Warning: Using placeholder keys. Run Supabase generate-keys.sh for production."
  ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlLWRlbW8iLCJpYXQiOjE2NDE3NjkyMDAsImV4cCI6MTc5OTUzNTYwMH0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE"
  SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UtZGVtbyIsImlhdCI6MTY0MTc2OTIwMCwiZXhwIjoxNzk5NTM1NjAwfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q"
fi

# API URL - use https if domain suggests it
API_URL="https://api.${DOMAIN}"
SITE_URL="https://${DOMAIN}"

# Create .env for this project
cat > "$PROJECT_DIR/.env" << ENVEOF
# Supabase project: $SLUG
# Generated by create-project.sh

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}

SECRET_KEY_BASE=${SECRET_KEY_BASE}
VAULT_ENC_KEY=${VAULT_ENC_KEY}
PG_META_CRYPTO_KEY=${PG_META_CRYPTO_KEY}
LOGFLARE_PUBLIC_ACCESS_TOKEN=${LOGFLARE_PUBLIC_ACCESS_TOKEN}
LOGFLARE_PRIVATE_ACCESS_TOKEN=${LOGFLARE_PRIVATE_ACCESS_TOKEN}

SUPABASE_PUBLIC_URL=${API_URL}
API_EXTERNAL_URL=${API_URL}
SITE_URL=${SITE_URL}
# Studio client API base - must match Kong/Studio origin for same-origin /api requests
NEXT_PUBLIC_SITE_URL=${API_URL}
ADDITIONAL_REDIRECT_URLS=https://${DOMAIN}/**,https://${DOMAIN}

MAILER_URLPATHS_CONFIRMATION="/auth/v1/verify"
MAILER_URLPATHS_INVITE="/auth/v1/verify"
MAILER_URLPATHS_RECOVERY="/auth/v1/verify"
MAILER_URLPATHS_EMAIL_CHANGE="/auth/v1/verify"

POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432

KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443

DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_ANONYMOUS_USERS=false
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false

JWT_EXPIRY=3600
PGRST_DB_SCHEMAS=public,storage,graphql_public
STORAGE_TENANT_ID=${SLUG}
REGION=local
GLOBAL_S3_BUCKET=supabase
POOLER_TENANT_ID=${SLUG}
POOLER_DEFAULT_POOL_SIZE=20
POOLER_MAX_CLIENT_CONN=100
POOLER_DB_POOL_SIZE=15
POOLER_PROXY_PORT_TRANSACTION=6543

STUDIO_DEFAULT_ORGANIZATION=Hosting
# Must be "default" to match Studio URL /project/default and lib/constants/api.ts DEFAULT_PROJECT.ref
STUDIO_DEFAULT_PROJECT=default
IMGPROXY_ENABLE_WEBP_DETECTION=true
FUNCTIONS_VERIFY_JWT=true

# Docker socket (required for functions)
DOCKER_SOCKET_LOCATION=/var/run/docker.sock

# S3/Storage protocol (required by docker-compose)
S3_PROTOCOL_ACCESS_KEY_ID=625729a08b95bf1b7ff351a663f3a23c
S3_PROTOCOL_ACCESS_KEY_SECRET=850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6eda37307425907

# SMTP (fake values for local - email auth will use inbucket)
SMTP_ADMIN_EMAIL=admin@${DOMAIN}
SMTP_HOST=supabase-mail
SMTP_PORT=2500
SMTP_USER=fake_mail_user
SMTP_PASS=fake_mail_password
SMTP_SENDER_NAME=Supabase

# Project identifier for container naming
PROJECT_SLUG=${SLUG}
ENVEOF

echo "Created $PROJECT_DIR/.env"

# Create override for unique container names and Traefik
mkdir -p "$PROJECT_DIR/volumes/api"
OVERRIDE="$PROJECT_DIR/docker-compose.override.yml"

# Kong config - update realtime host to project-specific container
REALTIME_HOST="supabase-${SLUG}-realtime"
cat "$SUPABASE_DIR/docker/volumes/api/kong.yml" 2>/dev/null | sed "s|realtime-dev.supabase-realtime|${REALTIME_HOST}|g" > "$PROJECT_DIR/volumes/api/kong.yml" 2>/dev/null || true

# Create override with project-scoped container names and Traefik
# Use absolute path for kong.yml so it works regardless of compose cwd
KONG_YAML="${PROJECT_DIR}/volumes/api/kong.yml"
mkdir -p "$(dirname "$KONG_YAML")"
if [ -f "$SUPABASE_DIR/docker/volumes/api/kong.yml" ]; then
  sed "s|realtime-dev.supabase-realtime|supabase-${SLUG}-realtime|g" \
    "$SUPABASE_DIR/docker/volumes/api/kong.yml" > "$KONG_YAML"
  # Add studio-api route without basic-auth (fetch does not send Basic Auth from page URL)
  if ! grep -q "name: studio-api" "$KONG_YAML" 2>/dev/null; then
    PATCH="  ## Studio API - no Basic Auth (fetch does not send URL credentials)
  - name: studio-api
    _comment: 'Studio API: /api/* -> Studio without basic-auth'
    url: http://studio:3000/
    routes:
      - name: studio-api-route
        strip_path: false
        paths:
          - /api/
    plugins:
      - name: cors

"
    # Insert before "## Protected Dashboard"
    awk -v patch="$PATCH" '/## Protected Dashboard - catch all/ { print patch; print; next } 1' "$KONG_YAML" > "$KONG_YAML.tmp" && mv "$KONG_YAML.tmp" "$KONG_YAML"
  fi
else
  echo "# Kong config placeholder - copy from Supabase repo" > "$KONG_YAML"
fi

cat > "$OVERRIDE" << OVEREOF
# Per-project override: unique containers + Traefik routing
# Generated for slug: ${SLUG}, domain: ${DOMAIN}

services:
  kong:
    container_name: supabase-${SLUG}-kong
    ports: []
    volumes:
      - ${KONG_YAML}:/home/kong/temp.yml:ro,z
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=hosting_network"
      - "traefik.http.routers.supabase-${SLUG}.rule=Host(\`api.${DOMAIN}\`)"
      - "traefik.http.routers.supabase-${SLUG}.entrypoints=websecure,web"
      - "traefik.http.routers.supabase-${SLUG}.service=supabase-${SLUG}-kong"
      - "traefik.http.routers.supabase-${SLUG}.tls=true"
      - "traefik.http.routers.supabase-${SLUG}.tls.certresolver=letsencrypt"
      - "traefik.http.routers.supabase-${SLUG}.tls.options=default"
      - "traefik.http.services.supabase-${SLUG}-kong.loadbalancer.server.port=8000"
    networks:
      - default
      - hosting_network

  db:
    container_name: supabase-${SLUG}-db
    volumes:
      - supabase_${SLUG}_db_data:/var/lib/postgresql/data
      - supabase_${SLUG}_db_config:/etc/postgresql-custom

  auth:
    container_name: supabase-${SLUG}-auth

  rest:
    container_name: supabase-${SLUG}-rest

  realtime:
    container_name: supabase-${SLUG}-realtime

  storage:
    container_name: supabase-${SLUG}-storage
    volumes:
      - supabase_${SLUG}_storage:/var/lib/storage:z

  imgproxy:
    container_name: supabase-${SLUG}-imgproxy
    volumes:
      - supabase_${SLUG}_storage:/var/lib/storage:z

  meta:
    container_name: supabase-${SLUG}-meta

  studio:
    container_name: supabase-${SLUG}-studio
    environment:
      NEXT_PUBLIC_SITE_URL: ${API_URL}

  analytics:
    container_name: supabase-${SLUG}-analytics

  functions:
    container_name: supabase-${SLUG}-functions

  supavisor:
    container_name: supabase-${SLUG}-pooler

  vector:
    container_name: supabase-${SLUG}-vector

volumes:
  supabase_${SLUG}_db_data:
  supabase_${SLUG}_db_config:
  supabase_${SLUG}_storage:

networks:
  hosting_network:
    external: true
OVEREOF

# Copy required volume files from Supabase into project (db init scripts, etc.)
for f in db/realtime.sql db/webhooks.sql db/roles.sql db/jwt.sql db/_supabase.sql db/logs.sql db/pooler.sql pooler/pooler.exs logs/vector.yml; do
  src="$SUPABASE_DIR/docker/volumes/$f"
  dst="$PROJECT_DIR/volumes/$f"
  if [ -f "$src" ]; then
    mkdir -p "$(dirname "$dst")"
    cp "$src" "$dst"
  fi
done

# Supabase db expects init scripts at ./volumes/db/ - we need to either copy to supabase dir
# or override db volumes. The base compose mounts ./volumes/db/* from supabase/docker/volumes.
# Our override replaces db data volume but not the init script mounts. The base has:
# - ./volumes/db/realtime.sql, etc.
# So we need those in supabase/docker/volumes. They're in the repo. We'll run from supabase/docker.
# The base compose's db uses supabase/docker/volumes - that's fine, those are shared.
# Our override only replaces the data volume. Good.

echo ""
echo "Starting Supabase for $SLUG..."
cd "$SUPABASE_DIR/docker"

# Run with project name and env file
docker compose -p "supabase-${SLUG}" \
  -f docker-compose.yml \
  -f "$PROJECT_DIR/docker-compose.override.yml" \
  --env-file "$PROJECT_DIR/.env" \
  up -d

echo ""
echo "=== Supabase project '$SLUG' created ==="
echo ""
echo "API URL: ${API_URL}"
echo "Add to your app's .env:"
echo "  VITE_SUPABASE_URL=${API_URL}"
echo "  VITE_SUPABASE_ANON_KEY=<see $PROJECT_DIR/.env ANON_KEY>"
echo ""
echo "Run migrations:"
echo "  docker exec -i supabase-${SLUG}-db psql -U postgres < your-migrations.sql"
echo ""
