#!/bin/bash
# Setup shared Supabase stack (one-time, like MySQL server).
# Usage: ./setup-shared-supabase.sh [domain]
#   domain: base domain for shared API/Studio, e.g. pdfsaas.com
#   Result: Studio at https://supabase.{domain}, API at https://api.supabase.{domain}
#
# Run from main page. Projects then use add-project-to-supabase.sh.

set -e

BASE_DOMAIN="${1:-}"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SHARED_DIR="${SCRIPT_DIR}/shared"
SUPABASE_DIR="${SCRIPT_DIR}/supabase"

if [ -z "$BASE_DOMAIN" ]; then
  echo "Usage: $0 <base_domain>"
  echo "Example: $0 pdfsaas.com"
  echo "  Creates: https://api.supabase.pdfsaas.com (API), https://supabase.pdfsaas.com (Studio)"
  exit 1
fi

# Slug for shared stack
SLUG="shared"
API_DOMAIN="api.supabase.${BASE_DOMAIN}"
STUDIO_DOMAIN="supabase.${BASE_DOMAIN}"
API_URL="https://${API_DOMAIN}"
SITE_URL="https://${STUDIO_DOMAIN}"

echo "Setting up shared Supabase stack for ${API_DOMAIN}"

# Check if already running
if docker ps --format '{{.Names}}' 2>/dev/null | grep -q '^supabase-shared-db$'; then
  echo "Shared Supabase is already running. Use add-project-to-supabase.sh for new projects."
  exit 0
fi

mkdir -p "$SHARED_DIR"
mkdir -p "$SHARED_DIR/volumes/api"

# Preserve existing secrets if retrying
if [ -f "$SHARED_DIR/.env" ]; then
  echo "Preserving existing secrets..."
  for key in POSTGRES_PASSWORD JWT_SECRET ANON_KEY SERVICE_ROLE_KEY SECRET_KEY_BASE VAULT_ENC_KEY PG_META_CRYPTO_KEY LOGFLARE_PUBLIC_ACCESS_TOKEN LOGFLARE_PRIVATE_ACCESS_TOKEN DASHBOARD_PASSWORD; do
    val=$(grep -E "^${key}=" "$SHARED_DIR/.env" 2>/dev/null | cut -d= -f2-)
    [ -n "$val" ] && export "$key=$val"
  done
fi

# Clone Supabase if needed
if [ ! -d "$SUPABASE_DIR/docker" ]; then
  if [ ! -d "$SUPABASE_DIR" ]; then
    echo "Cloning Supabase docker..."
    git clone --depth 1 https://github.com/supabase/supabase.git "$SUPABASE_DIR"
  else
    echo "Supabase repo incomplete. Remove and retry: rm -rf $SUPABASE_DIR"
    exit 1
  fi
fi

# Generate secrets
if [ -f "$SUPABASE_DIR/docker/utils/generate-keys.sh" ]; then
  KEY_OUTPUT=$(cd "$SUPABASE_DIR/docker" && ./utils/generate-keys.sh 2>/dev/null || true)
  if [ -n "$KEY_OUTPUT" ]; then
    eval "$(echo "$KEY_OUTPUT" | grep -E '^(JWT_SECRET|ANON_KEY|SERVICE_ROLE_KEY|SECRET_KEY_BASE|VAULT_ENC_KEY|PG_META_CRYPTO_KEY|LOGFLARE_PUBLIC_ACCESS_TOKEN|LOGFLARE_PRIVATE_ACCESS_TOKEN|POSTGRES_PASSWORD|DASHBOARD_PASSWORD)=')"
  fi
fi

: "${JWT_SECRET:=$(openssl rand -base64 48 | tr -d '\n' | head -c 64)}"
: "${POSTGRES_PASSWORD:=$(openssl rand -hex 16)}"
: "${SECRET_KEY_BASE:=$(openssl rand -base64 48 | tr -d '\n')}"
: "${VAULT_ENC_KEY:=$(openssl rand -hex 16)}"
: "${PG_META_CRYPTO_KEY:=$(openssl rand -base64 24 | tr -d '\n')}"
: "${LOGFLARE_PUBLIC_ACCESS_TOKEN:=$(openssl rand -hex 16)}"
: "${LOGFLARE_PRIVATE_ACCESS_TOKEN:=$(openssl rand -hex 16)}"
: "${DASHBOARD_PASSWORD:=$(openssl rand -hex 16)}"

if [ -z "$ANON_KEY" ] || [ "${#ANON_KEY}" -lt 50 ]; then
  ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlLWRlbW8iLCJpYXQiOjE2NDE3NjkyMDAsImV4cCI6MTc5OTUzNTYwMH0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE"
  SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoic2VydmljZV9yb2xlIiwiaXNzIjoic3VwYWJhc2UtZGVtbyIsImlhdCI6MTY0MTc2OTIwMCwiZXhwIjoxNzk5NTM1NjAwfQ.DaYlNEoUrrEn2Ig7tqibS-PHK5vgusbcbo7X36XVt4Q"
fi

# Create .env
cat > "$SHARED_DIR/.env" << ENVEOF
# Shared Supabase stack
# Generated by setup-shared-supabase.sh

POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
JWT_SECRET=${JWT_SECRET}
ANON_KEY=${ANON_KEY}
SERVICE_ROLE_KEY=${SERVICE_ROLE_KEY}
DASHBOARD_USERNAME=supabase
DASHBOARD_PASSWORD=${DASHBOARD_PASSWORD}

SECRET_KEY_BASE=${SECRET_KEY_BASE}
VAULT_ENC_KEY=${VAULT_ENC_KEY}
PG_META_CRYPTO_KEY=${PG_META_CRYPTO_KEY}
LOGFLARE_PUBLIC_ACCESS_TOKEN=${LOGFLARE_PUBLIC_ACCESS_TOKEN}
LOGFLARE_PRIVATE_ACCESS_TOKEN=${LOGFLARE_PRIVATE_ACCESS_TOKEN}

SUPABASE_PUBLIC_URL=${API_URL}
API_EXTERNAL_URL=${API_URL}
SITE_URL=${SITE_URL}
NEXT_PUBLIC_SITE_URL=${API_URL}
ADDITIONAL_REDIRECT_URLS=https://${STUDIO_DOMAIN}/**

MAILER_URLPATHS_CONFIRMATION="/auth/v1/verify"
MAILER_URLPATHS_INVITE="/auth/v1/verify"
MAILER_URLPATHS_RECOVERY="/auth/v1/verify"
MAILER_URLPATHS_EMAIL_CHANGE="/auth/v1/verify"

POSTGRES_HOST=db
POSTGRES_DB=postgres
POSTGRES_PORT=5432

KONG_HTTP_PORT=8000
KONG_HTTPS_PORT=8443

DISABLE_SIGNUP=false
ENABLE_EMAIL_SIGNUP=true
ENABLE_EMAIL_AUTOCONFIRM=true
ENABLE_ANONYMOUS_USERS=false
ENABLE_PHONE_SIGNUP=false
ENABLE_PHONE_AUTOCONFIRM=false

JWT_EXPIRY=3600
PGRST_DB_SCHEMAS=public,storage,graphql_public
STORAGE_TENANT_ID=shared
REGION=local
GLOBAL_S3_BUCKET=supabase
POOLER_TENANT_ID=shared
POOLER_DEFAULT_POOL_SIZE=20
POOLER_MAX_CLIENT_CONN=100
POOLER_DB_POOL_SIZE=15
POOLER_PROXY_PORT_TRANSACTION=6543

STUDIO_DEFAULT_ORGANIZATION=Hosting
STUDIO_DEFAULT_PROJECT=default
IMGPROXY_ENABLE_WEBP_DETECTION=true
FUNCTIONS_VERIFY_JWT=true

DOCKER_SOCKET_LOCATION=/var/run/docker.sock

S3_PROTOCOL_ACCESS_KEY_ID=625729a08b95bf1b7ff351a663f3a23c
S3_PROTOCOL_ACCESS_KEY_SECRET=850181e4652dd023b7a98c58ae0d2d34bd487ee0cc3254aed6eda37307425907

SMTP_ADMIN_EMAIL=admin@${STUDIO_DOMAIN}
SMTP_HOST=supabase-mail
SMTP_PORT=2500
SMTP_USER=fake_mail_user
SMTP_PASS=fake_mail_password
SMTP_SENDER_NAME=Supabase

# For add-project scripts
SUPABASE_SHARED_BASE_DOMAIN=${BASE_DOMAIN}
SUPABASE_SHARED_API_DOMAIN=${API_DOMAIN}
ENVEOF

# Kong config - shared realtime host
mkdir -p "$SHARED_DIR/volumes/api"
sed "s|realtime-dev.supabase-realtime|supabase-shared-realtime|g" \
  "$SUPABASE_DIR/docker/volumes/api/kong.yml" > "$SHARED_DIR/volumes/api/kong-base.yml"

# Add studio-api route if missing
if ! grep -q "name: studio-api" "$SHARED_DIR/volumes/api/kong-base.yml" 2>/dev/null; then
  PATCH="  - name: studio-api
    _comment: 'Studio API: /api/* -> Studio without basic-auth'
    url: http://studio:3000/
    routes:
      - name: studio-api-route
        strip_path: false
        paths:
          - /api/
    plugins:
      - name: cors

"
  awk -v patch="$PATCH" '/## Protected Dashboard - catch all/ { print patch; print; next } 1' \
    "$SHARED_DIR/volumes/api/kong-base.yml" > "$SHARED_DIR/volumes/api/kong-base.yml.tmp" && mv "$SHARED_DIR/volumes/api/kong-base.yml.tmp" "$SHARED_DIR/volumes/api/kong-base.yml"
fi
# Initial kong.yml = kong-base (no projects yet)
cp "$SHARED_DIR/volumes/api/kong-base.yml" "$SHARED_DIR/volumes/api/kong.yml"

# Compose override: shared container names + Traefik
cat > "$SHARED_DIR/docker-compose.override.yml" << OVEREOF
# Shared Supabase stack - one setup for all projects
# Kong routes api.supabase.${BASE_DOMAIN} (Studio/API)

services:
  kong:
    container_name: supabase-shared-kong
    ports: !reset []
    volumes:
      - "${SHARED_DIR}/volumes/api/kong.yml:/home/kong/temp.yml:ro,z"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=hosting_network"
      - "traefik.http.routers.supabase-shared.rule=Host(\`${API_DOMAIN}\`) || Host(\`${STUDIO_DOMAIN}\`)"
      - "traefik.http.routers.supabase-shared.entrypoints=websecure,web"
      - "traefik.http.routers.supabase-shared.service=supabase-shared-kong"
      - "traefik.http.routers.supabase-shared.tls=true"
      - "traefik.http.routers.supabase-shared.tls.certresolver=letsencrypt"
      - "traefik.http.services.supabase-shared-kong.loadbalancer.server.port=8000"
    networks:
      - default
      - hosting_network

  db:
    container_name: supabase-shared-db
    volumes:
      - supabase_shared_db_data:/var/lib/postgresql/data
      - supabase_shared_db_config:/etc/postgresql-custom

  auth:
    container_name: supabase-shared-auth
  rest:
    container_name: supabase-shared-rest
  realtime:
    container_name: supabase-shared-realtime
  storage:
    container_name: supabase-shared-storage
    volumes:
      - supabase_shared_storage:/var/lib/storage:z
  imgproxy:
    container_name: supabase-shared-imgproxy
    volumes:
      - supabase_shared_storage:/var/lib/storage:z
  meta:
    container_name: supabase-shared-meta
  studio:
    container_name: supabase-shared-studio
    environment:
      NEXT_PUBLIC_SITE_URL: ${API_URL}
  analytics:
    container_name: supabase-shared-analytics
  functions:
    container_name: supabase-shared-functions
  supavisor:
    container_name: supabase-shared-pooler
  vector:
    container_name: supabase-shared-vector

volumes:
  supabase_shared_db_data:
  supabase_shared_db_config:
  supabase_shared_storage:

networks:
  hosting_network:
    external: true
OVEREOF

# Ensure network
docker network create hosting_network 2>/dev/null || true

# Start shared stack
cd "$SUPABASE_DIR/docker"
docker compose -p "supabase-shared" \
  -f docker-compose.yml \
  -f "$SHARED_DIR/docker-compose.override.yml" \
  --env-file "$SHARED_DIR/.env" \
  up -d

# Write hosts file for Traefik routing (add-project appends new project hosts)
echo "${API_DOMAIN}" > "$SHARED_DIR/kong-hosts.txt"
echo "${STUDIO_DOMAIN}" >> "$SHARED_DIR/kong-hosts.txt"

# Regenerate override with hosts from file (in case we add a regen step)
"${SCRIPT_DIR}/regen-kong-and-override.sh" 2>/dev/null || true

echo ""
echo "=== Shared Supabase stack is ready ==="
echo ""
echo "Studio: https://${STUDIO_DOMAIN} (user: supabase, pass: see shared/.env DASHBOARD_PASSWORD)"
echo "API:    https://${API_DOMAIN}"
echo ""
echo "Add projects with: ./add-project-to-supabase.sh <slug> <domain>"
echo ""
